# TEC prediction data analysis

In [1]:
import pandas as pd
tec_data = pd.read_csv('data_to_kaggle.csv')

In [2]:
tec_data.head()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,...,X_182,X_183,X_184,X_185,X_186,X_187,X_188,X_189,X_190,Y
0,0.000007,0.000111,0.000042,0.000025,0.000041,0.000036,0.000041,0.000067,0.000059,0.000047,...,0.002433,0.002328,0.002529,0.002176,0.002484,0.002867,0.003239,0.003093,0.002434,6.929860
1,0.000009,0.000117,0.000043,0.000026,0.000042,0.000037,0.000041,0.000068,0.000060,0.000049,...,0.002366,0.002279,0.002472,0.002102,0.002454,0.002722,0.003207,0.003032,0.002371,8.184674
2,0.000007,0.000108,0.000041,0.000025,0.000040,0.000036,0.000040,0.000065,0.000058,0.000047,...,0.002341,0.002244,0.002388,0.002181,0.002489,0.002805,0.003136,0.003050,0.002326,8.184674
3,0.000006,0.000101,0.000039,0.000023,0.000039,0.000034,0.000038,0.000061,0.000054,0.000044,...,0.002377,0.002219,0.002374,0.002075,0.002513,0.002640,0.003370,0.003085,0.002306,8.877294
4,0.000006,0.000094,0.000038,0.000023,0.000038,0.000033,0.000037,0.000060,0.000053,0.000044,...,0.002402,0.002315,0.002511,0.002178,0.002527,0.002922,0.003164,0.003185,0.002352,9.433278

In [3]:
tec_data.describe()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,...,X_182,X_183,X_184,X_185,X_186,X_187,X_188,X_189,X_190,Y
count,1.217000e+03,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,...,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000
mean,1.944088e-06,0.000032,0.000019,0.000012,0.000021,0.000019,0.000021,0.000028,0.000026,0.000023,...,0.002118,0.002059,0.002203,0.001942,0.002203,0.002551,0.002861,0.002779,0.002167,12.711035
std,1.580567e-06,0.000023,0.000007,0.000004,0.000006,0.000005,0.000006,0.000011,0.000009,0.000007,...,0.000311,0.000297,0.000321,0.000279,0.000316,0.000367,0.000413,0.000403,0.000329,3.523191
min,3.434608e-07,0.000008,0.000006,0.000004,0.000007,0.000007,0.000007,0.000008,0.000008,0.000008,...,0.001470,0.001455,0.001592,0.001385,0.001583,0.001804,0.002071,0.001991,0.001440,5.289422
25%,8.795592e-07,0.000017,0.000014,0.000009,0.000017,0.000015,0.000017,0.000021,0.000020,0.000018,...,0.001812,0.001763,0.001879,0.001655,0.001881,0.002186,0.002452,0.002376,0.001865,9.987565
50%,1.447348e-06,0.000025,0.000017,0.000011,0.000020,0.000018,0.000020,0.000025,0.000024,0.000022,...,0.002182,0.002117,0.002281,0.002015,0.002286,0.002642,0.002924,0.002851,0.002200,12.705798
75%,2.408093e-06,0.000040,0.000021,0.000014,0.000023,0.000021,0.000023,0.000032,0.000030,0.000026,...,0.002384,0.002328,0.002506,0.002200,0.002493,0.002882,0.003233,0.003154,0.002454,15.002869
max,9.695057e-06,0.000150,0.000051,0.000030,0.000048,0.000042,0.000048,0.000080,0.000070,0.000055,...,0.002890,0.002712,0.002834,0.002447,0.002759,0.003267,0.003616,0.003516,0.002918,24.617175

In [4]:
tec_data.columns

Index(['X_1', 'X_2', 'X_3', 'X_4', 'X_5', 'X_6', 'X_7', 'X_8', 'X_9', 'X_10',
       ...
       'X_182', 'X_183', 'X_184', 'X_185', 'X_186', 'X_187', 'X_188', 'X_189',
       'X_190', 'Y'],
      dtype='object', length=191)

In [5]:
X = tec_data['Y']

In [6]:
features = ['X_1', 'X_2', 'X_3', 'X_4', 'X_5', 'X_6', 'X_7', 'X_8', 'X_9', 'X_10', 'X_11', 'X_12', 'X_13', 'X_14', 'X_15', 'X_16', 'X_17', 'X_18', 'X_19', 'X_20', 'X_21', 'X_22', 'X_23', 'X_24', 'X_25', 'X_26', 'X_27', 'X_28', 'X_29', 'X_30', 'X_31', 'X_32', 'X_33', 'X_34', 'X_35', 'X_36', 'X_37', 'X_38', 'X_39', 'X_40', 'X_41', 'X_42', 'X_43', 'X_44', 'X_45', 'X_46', 'X_47', 'X_48', 'X_49', 'X_50', 'X_51', 'X_52', 'X_53', 'X_54', 'X_55', 'X_56', 'X_57', 'X_58', 'X_59', 'X_60', 'X_61', 'X_62', 'X_63', 'X_64', 'X_65', 'X_66', 'X_67', 'X_68', 'X_69', 'X_70', 'X_71', 'X_72', 'X_73', 'X_74', 'X_75', 'X_76', 'X_77', 'X_78', 'X_79', 'X_80', 'X_81', 'X_82', 'X_83', 'X_84', 'X_85', 'X_86', 'X_87', 'X_88', 'X_89', 'X_90', 'X_91', 'X_92', 'X_93', 'X_94', 'X_95', 'X_96', 'X_97', 'X_98', 'X_99', 'X_100', 'X_101', 'X_102', 'X_103', 'X_104', 'X_105', 'X_106', 'X_107', 'X_108', 'X_109', 'X_110', 'X_111', 'X_112', 'X_113', 'X_114', 'X_115', 'X_116', 'X_117', 'X_118', 'X_119', 'X_120', 'X_121', 'X_122', 'X_123', 'X_124', 'X_125', 'X_126', 'X_127', 'X_128', 'X_129', 'X_130', 'X_131', 'X_132', 'X_133', 'X_134', 'X_135', 'X_136', 'X_137', 'X_138', 'X_139', 'X_140', 'X_141', 'X_142', 'X_143', 'X_144', 'X_145', 'X_146', 'X_147', 'X_148', 'X_149', 'X_150', 'X_151', 'X_152', 'X_153', 'X_154', 'X_155', 'X_156', 'X_157', 'X_158', 'X_159', 'X_160', 'X_161', 'X_162', 'X_163', 'X_164', 'X_165', 'X_166', 'X_167', 'X_168', 'X_169', 'X_170', 'X_171', 'X_172', 'X_173', 'X_174', 'X_175', 'X_176', 'X_177', 'X_178', 'X_179', 'X_180', 'X_181', 'X_182', 'X_183', 'X_184', 'X_185', 'X_186', 'X_187', 'X_188', 'X_189', 'X_190']
y = tec_data[features]

In [7]:
y.describe()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,...,X_181,X_182,X_183,X_184,X_185,X_186,X_187,X_188,X_189,X_190
count,1.217000e+03,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,...,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000
mean,1.944088e-06,0.000032,0.000019,0.000012,0.000021,0.000019,0.000021,0.000028,0.000026,0.000023,...,0.001796,0.002118,0.002059,0.002203,0.001942,0.002203,0.002551,0.002861,0.002779,0.002167
std,1.580567e-06,0.000023,0.000007,0.000004,0.000006,0.000005,0.000006,0.000011,0.000009,0.000007,...,0.000257,0.000311,0.000297,0.000321,0.000279,0.000316,0.000367,0.000413,0.000403,0.000329
min,3.434608e-07,0.000008,0.000006,0.000004,0.000007,0.000007,0.000007,0.000008,0.000008,0.000008,...,0.001294,0.001470,0.001455,0.001592,0.001385,0.001583,0.001804,0.002071,0.001991,0.001440
25%,8.795592e-07,0.000017,0.000014,0.000009,0.000017,0.000015,0.000017,0.000021,0.000020,0.000018,...,0.001529,0.001812,0.001763,0.001879,0.001655,0.001881,0.002186,0.002452,0.002376,0.001865
50%,1.447348e-06,0.000025,0.000017,0.000011,0.000020,0.000018,0.000020,0.000025,0.000024,0.000022,...,0.001866,0.002182,0.002117,0.002281,0.002015,0.002286,0.002642,0.002924,0.002851,0.002200
75%,2.408093e-06,0.000040,0.000021,0.000014,0.000023,0.000021,0.000023,0.000032,0.000030,0.000026,...,0.002035,0.002384,0.002328,0.002506,0.002200,0.002493,0.002882,0.003233,0.003154,0.002454
max,9.695057e-06,0.000150,0.000051,0.000030,0.000048,0.000042,0.000048,0.000080,0.000070,0.000055,...,0.002252,0.002890,0.002712,0.002834,0.002447,0.002759,0.003267,0.003616,0.003516,0.002918

In [8]:
tec_data.head()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,...,X_182,X_183,X_184,X_185,X_186,X_187,X_188,X_189,X_190,Y
0,0.000007,0.000111,0.000042,0.000025,0.000041,0.000036,0.000041,0.000067,0.000059,0.000047,...,0.002433,0.002328,0.002529,0.002176,0.002484,0.002867,0.003239,0.003093,0.002434,6.929860
1,0.000009,0.000117,0.000043,0.000026,0.000042,0.000037,0.000041,0.000068,0.000060,0.000049,...,0.002366,0.002279,0.002472,0.002102,0.002454,0.002722,0.003207,0.003032,0.002371,8.184674
2,0.000007,0.000108,0.000041,0.000025,0.000040,0.000036,0.000040,0.000065,0.000058,0.000047,...,0.002341,0.002244,0.002388,0.002181,0.002489,0.002805,0.003136,0.003050,0.002326,8.184674
3,0.000006,0.000101,0.000039,0.000023,0.000039,0.000034,0.000038,0.000061,0.000054,0.000044,...,0.002377,0.002219,0.002374,0.002075,0.002513,0.002640,0.003370,0.003085,0.002306,8.877294
4,0.000006,0.000094,0.000038,0.000023,0.000038,0.000033,0.000037,0.000060,0.000053,0.000044,...,0.002402,0.002315,0.002511,0.002178,0.002527,0.002922,0.003164,0.003185,0.002352,9.433278

In [9]:
y.describe()

,X_1,X_2,X_3,X_4,X_5,X_6,X_7,X_8,X_9,X_10,...,X_181,X_182,X_183,X_184,X_185,X_186,X_187,X_188,X_189,X_190
count,1.217000e+03,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,...,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000,1217.000000
mean,1.944088e-06,0.000032,0.000019,0.000012,0.000021,0.000019,0.000021,0.000028,0.000026,0.000023,...,0.001796,0.002118,0.002059,0.002203,0.001942,0.002203,0.002551,0.002861,0.002779,0.002167
std,1.580567e-06,0.000023,0.000007,0.000004,0.000006,0.000005,0.000006,0.000011,0.000009,0.000007,...,0.000257,0.000311,0.000297,0.000321,0.000279,0.000316,0.000367,0.000413,0.000403,0.000329
min,3.434608e-07,0.000008,0.000006,0.000004,0.000007,0.000007,0.000007,0.000008,0.000008,0.000008,...,0.001294,0.001470,0.001455,0.001592,0.001385,0.001583,0.001804,0.002071,0.001991,0.001440
25%,8.795592e-07,0.000017,0.000014,0.000009,0.000017,0.000015,0.000017,0.000021,0.000020,0.000018,...,0.001529,0.001812,0.001763,0.001879,0.001655,0.001881,0.002186,0.002452,0.002376,0.001865
50%,1.447348e-06,0.000025,0.000017,0.000011,0.000020,0.000018,0.000020,0.000025,0.000024,0.000022,...,0.001866,0.002182,0.002117,0.002281,0.002015,0.002286,0.002642,0.002924,0.002851,0.002200
75%,2.408093e-06,0.000040,0.000021,0.000014,0.000023,0.000021,0.000023,0.000032,0.000030,0.000026,...,0.002035,0.002384,0.002328,0.002506,0.002200,0.002493,0.002882,0.003233,0.003154,0.002454
max,9.695057e-06,0.000150,0.000051,0.000030,0.000048,0.000042,0.000048,0.000080,0.000070,0.000055,...,0.002252,0.002890,0.002712,0.002834,0.002447,0.002759,0.003267,0.003616,0.003516,0.002918

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_absolute_error

# X.shape should be (N, M) where M >= 1
# X = mydata[['script']]  
# y.shape should be (N, 1)
# y = mydata['label'] 
# perform label encoding if "label" contains strings
# y = pd.factorize(mydata['label'])[0].reshape(-1, 1) 
X_train, X_test, y_train, y_test = train_test_split(
                      X, y, test_size=0.33, random_state=1)

X_train = np.array(X_train)
X_train = X_train.reshape(-1,1)
X_test = np.array(X_test)
X_test = X_test.reshape(-1,1)

In [11]:
def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = RandomForestRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [12]:
candidate_max_leaf_nodes = [5, 25, 50, 100, 250, 500]
# Write loop to find the ideal tree size from candidate_max_leaf_nodes
scores = {leaf_size: get_mae(leaf_size, X_train, X_test, y_train, y_test) for leaf_size in candidate_max_leaf_nodes}

# Store the best value of max_leaf_nodes (it will be either 5, 25, 50, 100, 250 or 500)
best_tree_size = min(scores, key=scores.get)

In [13]:
scores

{5: 1.984147741344942e-05,
 25: 1.9605529680226634e-05,
 50: 1.9483884212985968e-05,
 100: 1.9888971358167725e-05,
 250: 2.0924534969299733e-05,
 500: 2.1186397784251786e-05}

In [14]:
best_tree_size

50

In [15]:
# Fill in argument to make optimal size and uncomment
final_model = RandomForestRegressor(max_leaf_nodes=50,random_state=1)

# fit the final model and uncomment the next two lines
final_model.fit(X_train, y_train)

RandomForestRegressor(max_leaf_nodes=50, random_state=1)

In [16]:
final_model.predict(X_test)

array([[1.82052444e-06, 3.21028468e-05, 1.99508334e-05, ...,
        3.26171769e-03, 3.17767276e-03, 2.48525914e-03],
       [2.71489113e-06, 4.43895226e-05, 2.12519445e-05, ...,
        2.64166689e-03, 2.55161907e-03, 1.92830387e-03],
       [2.20181141e-06, 3.62988524e-05, 1.84201248e-05, ...,
        2.41394221e-03, 2.33969464e-03, 1.77909082e-03],
       ...,
       [2.20643992e-06, 3.51786924e-05, 1.96487547e-05, ...,
        3.00270337e-03, 2.89495047e-03, 2.34400622e-03],
       [1.71045410e-06, 2.74553693e-05, 1.77153592e-05, ...,
        3.02794273e-03, 2.93924283e-03, 2.33208663e-03],
       [1.84767292e-06, 3.25900988e-05, 2.02451502e-05, ...,
        3.26868537e-03, 3.19327356e-03, 2.49371472e-03]])

In [17]:

# node_counts = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
# my_mae = {}
# for n_nodes in node_counts:
#   tec_model = DecisionTreeRegressor(max_leaf_nodes = n_nodes, random_state=1)
#   tec_model.fit(X_train, y_train)
#   tec_preds = tec_model.predict(X_test)
#   my_mae = {n_nodes : mean_absolute_error(y_test, tec_preds) for n_nodes in my_mae}

# from sklearn.tree import DecisionTreeRegressor
# tec_model = DecisionTreeRegressor(random_state=1)